# Функции в Pandas

In [2]:
import pandas as pd

In [83]:
df = pd.DataFrame({'Stud': ['Ivan','Petr', 'Maria'], 'Subject': ['Math', 'Hist', 'Georp'], 'Grade': [35, 75, 90]})
df

    Stud Subject  Grade
0   Ivan    Math     35
1   Petr    Hist     75
2  Maria   Georp     90

In [84]:
df = pd.DataFrame({'Stud': ['Ivan','Petr', 'Maria'], 'Subject': ['Math', 'Hist', 'Georp'], 'Grade': [35, 75, 90], 'EurGrade': ['F', 'C','A']})
df

    Stud Subject  Grade EurGrade
0   Ivan    Math     35        F
1   Petr    Hist     75        C
2  Maria   Georp     90        A

In [19]:
def change(grad):
    """Мне только посмотреть"""
    if grad < 60:
        return 'F'
    elif 60 < grad < 75:
        return 'E'
    elif 90>grad >=75:
        return 'C'
    elif grad >=90:
        return 'A'

In [85]:
df['anotherGrade'] = df['Grade'].apply(change)
df

    Stud Subject  Grade EurGrade anotherGrade
0   Ivan    Math     35        F            F
1   Petr    Hist     75        C            C
2  Maria   Georp     90        A            A

In [88]:
def density(row):
    return row['reyting'] / row['present']

### Как потестировать функцию со значениями одной строки

Применяем метод apply к датафрейму. В переменную функции передаются строки целиком

In [89]:
df = pd.DataFrame({'stud_id': [1, 2, 3], 'reyting': [97, 83, 75], 'present': [2, 4, 1]})
df

   stud_id  reyting  present
0        1       97        2
1        2       83        4
2        3       75        1

In [90]:
df['density'] = df.apply(density, axis=1)

In [91]:
df

   stud_id  reyting  present  density
0        1       97        2    48.50
1        2       83        4    20.75
2        3       75        1    75.00

### Lambda-функции
Хотим посчитать распределение количества слов в столбце с фразами

In [92]:
df['density_by_lambda'] = df['reyting'].apply(lambda x : x/5)

In [93]:
df

   stud_id  reyting  present  density  density_by_lambda
0        1       97        2    48.50               19.4
1        2       83        4    20.75               16.6
2        3       75        1    75.00               15.0

# Группировки

In [95]:
df = pd.DataFrame({'stud_id': [1, 2, 3, 4, 5], 'Subject': ['ТВиМС', 'МОР', 'ТВиМС', 'МОР', 'ТВиМС'], 
                   'amount': [100, 80, 90, 140, 90]})
df

   stud_id Subject  amount
0        1   ТВиМС     100
1        2     МОР      80
2        3   ТВиМС      90
3        4     МОР     140
4        5   ТВиМС      90

In [97]:
df_tvims = df[df.Subject == 'ТВиМС']
df_tvims

   stud_id Subject  amount
0        1   ТВиМС     100
2        3   ТВиМС      90
4        5   ТВиМС      90

In [98]:
df_mor = df[df.Subject == 'МОР']
df_mor

   stud_id Subject  amount
1        2     МОР      80
3        4     МОР     140

In [99]:
df_tvims.amount.mean()

93.33333333333333

In [78]:
df_mor.amount.mean()

110.0

In [100]:
df_tvims.amount.max() - df_tvims.amount.min()

10

In [101]:
df_mor.amount.max() - df_mor.amount.min()

60

Объединим процесс разбиения на датафреймы

In [81]:
def groupby_function(data):
    return data.amount.max() - data.amount.min()

In [82]:
df.groupby('Subject').apply(groupby_function)

Subject
МОР      60
ТВиМС    10
dtype: int64